language:
- node_js
node_js:
- 8.0.0
branches:
  only:
  - master
before_install:
- chmod 600 .travis/id_rsa
- openssl aes-256-cbc -K $encrypted_d839c941aa8f_key -iv $encrypted_d839c941aa8f_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- eval $(ssh-agent)
- ssh-add .travis/id_rsa
- git config --global user.name 'andyliwr'
- git config --global user.email andyliwr@outlook.com
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g -d
- ifconfig
