# 使用的语言
language:
 - node_js

# 使用的node版本
node_js:
 - "8.0.0"

# 仓库的分支
branches:
  only:
    - master

# 执行isntall前需要执行的命令
before_install:
  - openssl aes-256-cbc -K $encrypted_d839c941aa8f_key -iv $encrypted_d839c941aa8f_iv
    -in .travis/id_rsa_travis.enc -out .travis/id_rsa_travis -d

# 改变文件权限
  - chmod 600 .travis/id_rsa_travis

# 配置 ssh
  - eval $(ssh-agent)
  - ssh-add .travis/id_rsa_travis

# 配置git 的个人信息
  - git config --global user.name 'andyliwr'
  - git config --global user.email andyliwr@outlook.com

# 执行install
install:
  - alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc" # cnpm
  - cnpm install hexo-cli -g
  - cnpm install

# 执行命令脚本
script:
  - hexo clean
  - hexo g -d
