# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about/index.html

# Customize
customize:
    logo:
        width: 80
        height: 80
        url: images/logo-header.svg
    theme_color: '#006bde'
    highlight: highlightjs
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/images/favicon.ico # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        github: https://github.com/Andyliwr
        weibo: http://weibo.com/p/1005053777760803/home
        csdn: http://blog.csdn.net/u014374031

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan:
        appId: cyt9Qajra
        appKey: 9fa82ebb86771732bc648d702ba31a4b
        on: true

# Share
share: jiathis # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: 7851ca7a86be957be994acb77639a5be # enter Baidu Analytics hash key
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
